export const mockTransportationData = {
  performanceData: [
    { month: 'Jan', avgRating: 4.5, safetyScore: 92, violations: 3 },
    { month: 'Feb', avgRating: 4.6, safetyScore: 94, violations: 2 },
    { month: 'Mar', avgRating: 4.4, safetyScore: 91, violations: 4 },
    { month: 'Apr', avgRating: 4.7, safetyScore: 95, violations: 1 },
    { month: 'May', avgRating: 4.8, safetyScore: 96, violations: 2 },
    { month: 'Jun', avgRating: 4.6, safetyScore: 93, violations: 3 },
  ],
  experienceDistribution: [
    { experience: '0-2 years', count: 5 },
    { experience: '3-5 years', count: 12 },
    { experience: '6-10 years', count: 18 },
    { experience: '10+ years', count: 8 },
  ],
  trainingMetrics: [
    { skill: 'Safety', score: 92 },
    { skill: 'Navigation', score: 88 },
    { skill: 'Customer Service', score: 85 },
    { skill: 'Vehicle Maintenance', score: 78 },
    { skill: 'Emergency Response', score: 90 },
    { skill: 'Route Optimization', score: 82 },
  ],
  utilizationData: [
    { month: 'Jan', active: 42, maintenance: 4, available: 2 },
    { month: 'Feb', active: 45, maintenance: 2, available: 1 },
    { month: 'Mar', active: 43, maintenance: 3, available: 2 },
    { month: 'Apr', active: 46, maintenance: 1, available: 1 },
    { month: 'May', active: 44, maintenance: 3, available: 1 },
    { month: 'Jun', active: 47, maintenance: 1, available: 0 },
  ],
  vehicleAgeDistribution: [
    { age: '0-2 years', count: 18, fill: '#10b981' },
    { age: '2-5 years', count: 22, fill: '#3b82f6' },
    { age: '5-8 years', count: 6, fill: '#f59e0b' },
    { age: '8+ years', count: 2, fill: '#ef4444' },
  ],
  maintenanceCosts: [
    { month: 'Jan', cost: 12500 },
    { month: 'Feb', cost: 8900 },
    { month: 'Mar', cost: 15200 },
    { month: 'Apr', cost: 6700 },
    { month: 'May', cost: 11800 },
    { month: 'Jun', cost: 9200 },
  ],
  maintenanceStats: [
    { month: 'Jan', preventive: 8, corrective: 4, emergency: 2 },
    { month: 'Feb', preventive: 10, corrective: 3, emergency: 1 },
    { month: 'Mar', preventive: 12, corrective: 5, emergency: 3 },
    { month: 'Apr', preventive: 9, corrective: 2, emergency: 1 },
    { month: 'May', preventive: 11, corrective: 4, emergency: 2 },
    { month: 'Jun', preventive: 13, corrective: 3, emergency: 1 },
  ],
  costBreakdown: [
    { type: 'Preventive', cost: 12500, fill: '#10b981' },
    { type: 'Corrective', cost: 8900, fill: '#f59e0b' },
    { type: 'Emergency', cost: 15200, fill: '#ef4444' },
    { type: 'Inspection', cost: 3400, fill: '#3b82f6' },
  ],
  downtimeData: [
    { month: 'Jan', planned: 48, unplanned: 12 },
    { month: 'Feb', planned: 36, unplanned: 8 },
    { month: 'Mar', planned: 60, unplanned: 18 },
    { month: 'Apr', planned: 42, unplanned: 6 },
    { month: 'May', planned: 54, unplanned: 14 },
    { month: 'Jun', planned: 39, unplanned: 9 },
  ],
  monthlyConsumption: [
    { month: 'Jan', diesel: 1250, gasoline: 890, cost: 3150 },
    { month: 'Feb', diesel: 1180, gasoline: 820, cost: 2890 },
    { month: 'Mar', diesel: 1320, gasoline: 950, cost: 3420 },
    { month: 'Apr', diesel: 1090, gasoline: 780, cost: 2650 },
    { month: 'May', diesel: 1240, gasoline: 860, cost: 3080 },
    { month: 'Jun', diesel: 1150, gasoline: 800, cost: 2850 },
  ],
  fuelEfficiencyTrends: [
    { month: 'Jan', avgEfficiency: 11.2, target: 12.0 },
    { month: 'Feb', avgEfficiency: 11.8, target: 12.0 },
    { month: 'Mar', avgEfficiency: 11.5, target: 12.0 },
    { month: 'Apr', avgEfficiency: 12.1, target: 12.0 },
    { month: 'May', avgEfficiency: 12.3, target: 12.0 },
    { month: 'Jun', avgEfficiency: 12.5, target: 12.0 },
  ],
  stationUsage: [
    { station: 'Shell Downtown', usage: 32, fill: '#ef4444' },
    { station: 'BP Express', usage: 28, fill: '#10b981' },
    { station: 'Petro Canada', usage: 24, fill: '#3b82f6' },
    { station: 'Esso', usage: 16, fill: '#f59e0b' },
  ],
  fuelCostBreakdown: [
    { category: 'Fuel', amount: 18500 },
    { category: 'Service Charges', amount: 750 },
    { category: 'Card Fees', amount: 240 },
    { category: 'Environmental Fees', amount: 180 },
  ],
  routeEfficiencyTrends: [
    { month: 'Jan', efficiency: 85, fuelSaved: 12 },
    { month: 'Feb', efficiency: 88, fuelSaved: 18 },
    { month: 'Mar', efficiency: 87, fuelSaved: 15 },
    { month: 'Apr', efficiency: 91, fuelSaved: 22 },
    { month: 'May', efficiency: 89, fuelSaved: 19 },
    { month: 'Jun', efficiency: 93, fuelSaved: 28 },
  ],
  timeVsDistance: [
    { route: 'Downtown', distance: 15.2, time: 38 },
    { route: 'Airport', distance: 28.5, time: 42 },
    { route: 'Industrial', distance: 22.8, time: 48 },
    { route: 'Residential', distance: 18.7, time: 35 },
    { route: 'Express', distance: 35.2, time: 55 },
    { route: 'Local', distance: 12.3, time: 28 },
  ],
  trafficPatterns: [
    { hour: '06:00', light: 15, moderate: 25, heavy: 60 },
    { hour: '08:00', light: 10, moderate: 30, heavy: 60 },
    { hour: '10:00', light: 40, moderate: 35, heavy: 25 },
    { hour: '12:00', light: 25, moderate: 40, heavy: 35 },
    { hour: '14:00', light: 35, moderate: 35, heavy: 30 },
    { hour: '16:00', light: 15, moderate: 25, heavy: 60 },
    { hour: '18:00', light: 8, moderate: 22, heavy: 70 },
    { hour: '20:00', light: 55, moderate: 30, heavy: 15 },
  ],
  routeTypes: [
    { name: 'Urban', value: 35, fill: '#3b82f6' },
    { name: 'Highway', value: 28, fill: '#10b981' },
    { name: 'Mixed', value: 25, fill: '#f59e0b' },
    { name: 'Rural', value: 12, fill: '#8b5cf6' },
  ],
  fuelConsumptionData: [
    { month: 'Jan', consumption: 2400, cost: 3600 },
    { month: 'Feb', consumption: 2210, cost: 3315 },
    { month: 'Mar', consumption: 2290, cost: 3435 },
    { month: 'Apr', consumption: 2000, cost: 3000 },
    { month: 'May', consumption: 2181, cost: 3272 },
    { month: 'Jun', consumption: 2500, cost: 3750 }
  ],
  maintenanceScheduleData: [
    { week: 'Week 1', scheduled: 12, completed: 10, overdue: 2 },
    { week: 'Week 2', scheduled: 15, completed: 13, overdue: 1 },
    { week: 'Week 3', scheduled: 18, completed: 16, overdue: 3 },
    { week: 'Week 4', scheduled: 14, completed: 12, overdue: 1 }
  ]
};
